[package]
name = "rabbitmq-rust-app-consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.5.0"
tokio = { version = "1.41.1", features = ["full"] }
env_logger = "0.11.5"
log = "0.4"
futures-util = "0.3.31"
