apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-rust-app
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-creds
  namespace: rabbitmq-rust-app
type: Opaque
stringData:
  username: user
  password: password
  uri: http://rabbitmq.rabbitmq.svc.cluster.local:15672
  rabbitmq_url: amqp://user:password@rabbitmq.rabbitmq.svc.cluster.local:5672
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rabbitmq-rust-app-cronjob
  namespace: rabbitmq-rust-app
spec:
  schedule: "* * * * *" # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rabbitmq-rust-app
            image: hortonew/rabbitmq-rust-app:0.0.8
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-creds
                  key: username
            - name: RUST_LOG
              value: info
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-creds
                  key: password
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbit-creds
                  key: rabbitmq_url
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://pyroscope.pyroscope.svc.cluster.local:4040"
            - name: PYROSCOPE_APPLICATION_NAME
              value: "rabbitmq-rust-producer"
          restartPolicy: OnFailure
