apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: rabbitmq-rust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: rabbitmq-consumer
        image: hortonew/rabbitmq-rust-app-consumer:0.0.4
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbit-creds
              key: rabbitmq_url
        - name: RUST_LOG
          value: info
        - name: PYROSCOPE_SERVER_ADDRESS
          value: "http://pyroscope.pyroscope.svc.cluster.local:4040"
        - name: PYROSCOPE_APPLICATION_NAME
          value: "rabbitmq-rust-consumer"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
